
server:
  port: 7090
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: spotify
  domain: http://localhost:9081
  serverUrl: http://localhost:9081
  adminClientId: admin-cli
  adminClientSecret: VBcbPmiylEY4XDq7SatEZN0kcSuI8xUv
  client: authenticationClientId
spring:
  profile:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}
