server:
  port: 7093
  servlet:
    context-path: /user

app:
  dbHostName: localhost
  dbPort: 5432  # Ensure this is correct for PostgreSQL
  dbUsername: postgres
  dbPassword: root
  dbName: spotify

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Optional logging configuration
logging:
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Custom console logging format
