
server:
  port: 7093
  servlet:
    context-path: /user

app:
  dbHostName: localhost
  dbPort: 3306
  dbUsername: postgres
  dbPassword: root
  dbName: spotify

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spotify
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# Optional logging configuration

